/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rangelist;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class RangeListTest {
    @Test
    void addRemoveRanges() {
        RangeList classUnderTest = new RangeList();
        classUnderTest.add(new int[] { 1, 5 });
        assertEquals("[1, 5)", classUnderTest.toString());
        classUnderTest.add(new int[] { 10, 20 });
        assertEquals("[1, 5) [10, 20)", classUnderTest.toString());
        classUnderTest.add(new int[] { 20, 20 });
        assertEquals("[1, 5) [10, 20)", classUnderTest.toString());
        classUnderTest.add(new int[] { 20, 21 });
        assertEquals("[1, 5) [10, 21)", classUnderTest.toString());
        classUnderTest.add(new int[] { 2, 4 });
        assertEquals("[1, 5) [10, 21)", classUnderTest.toString());
        classUnderTest.add(new int[] { 3, 8 });
        assertEquals("[1, 8) [10, 21)", classUnderTest.toString());

        classUnderTest.remove(new int[] { 10, 10 });
        assertEquals("[1, 8) [10, 21)", classUnderTest.toString());
        classUnderTest.remove(new int[] { 10, 11 });
        assertEquals("[1, 8) [11, 21)", classUnderTest.toString());
        classUnderTest.remove(new int[] { 15, 17 });
        assertEquals("[1, 8) [11, 15) [17, 21)", classUnderTest.toString());
        classUnderTest.remove(new int[] { 3, 19 });
        assertEquals("[1, 3) [19, 21)", classUnderTest.toString());
    }

    @Test
    void emptyRange() {
        RangeList classUnderTest = new RangeList();
        assertEquals("", classUnderTest.toString());
    }
}
